name: "introspect"
on:
  push:
    branches:
      - main
jobs:
  introspect:
    runs-on: ubuntu-latest
    services:
      apollo:
        image: danielsinclair/apollo-example
    steps:
    - name: health check
      run: curl http://apollo:3000/.well-known/apollo/server-health
    - uses: actions/checkout@v2
    - name: rover introspect
      id: introspect
      uses: ./
      with:
        federated: true
        subgraph: products
        server: http://apollo:3000/
      env:
        APOLLO_KEY: ${{ secrets.APOLLO_KEY }}
    - run: cat ${{ steps.introspect.outputs.path }}