name: "introspect"
on:
  push:
    branches:
      - main
jobs:
  introspect:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: introspect
    services:
      apollo:
        image: danielsinclair/apollo-example
    steps:
    - uses: actions/checkout@v2
    - name: rover introspect
      id: introspect
      uses: ./
      with:
        federated: true
        subgraph: products
        server: http://apollo:3000/
      env:
        APOLLO_KEY: ${{ secrets.APOLLO_KEY }}
    - uses: actions/upload-artifact@v2
      with:
        name: products.graphql
        path: ${{ steps.introspect.outputs.path }}
  artifact:
    needs: introspect
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v2
      with:
        name: products.graphql
    - run: cat products.graphql